from ai.factory.live_order_authority import submit_legacy_order
#!/usr/bin/env python3
"""
INTEGRAFIX: ABCFC Live Nexus
============================

PROBLEM:
The theoretical ABCFC Nexus Cloud generates abstract futures but lacks:
1. Connection to real market data (Polymarket prices, order books)
2. Actual probability estimates (uses hardcoded 50%)
3. Executable action generation (no real trading opportunities)
4. Feedback loop (outcomes don't feed back to learning)

SOLUTION:
This bridge wires theoretical ABCFC to practical trading by:
1. OBSERVE: Pull real positions and market data
2. GENERATE: Create executable actions from real opportunities
3. SIMULATE: Use actual probabilities and order book depth
4. DECIDE: Score with real expected values
5. EXECUTE: Place actual trades (or dry run)
6. TRACK: Record outcomes and update learning

ARCHITECTURE:
=============
              ┌─────────────────────────────────────────────────┐
              │            ABCFC LIVE NEXUS                      │
              └─────────────────────────────────────────────────┘
                               │
        ┌──────────────────────┼──────────────────────┐
        │                      │                      │
        ▼                      ▼                      ▼
┌───────────────┐      ┌───────────────┐      ┌───────────────┐
│  MARKET DATA  │      │  ABCFC THEORY │      │  EXECUTION    │
│               │      │               │      │               │
│  • Polymarket │ ───► │  • Hierarchy  │ ───► │  • Trade API  │
│  • Order books│      │  • Nexus Cloud│      │  • Position   │
│  • Prices     │      │  • Scoring    │      │  • Outcome    │
└───────────────┘      └───────────────┘      └───────────────┘
        │                      │                      │
        └──────────────────────┼──────────────────────┘
                               │
                               ▼
                       ┌───────────────┐
                       │   LEARNING    │
                       │               │
                       │  • Calibrate  │
                       │  • Improve    │
                       └───────────────┘

Serving: Yair Siegel
"""

import os
import json
from pathlib import Path
from datetime import datetime, timezone
from typing import Dict, List, Optional, Tuple, Any
from dataclasses import dataclass, field
from enum import Enum

PROJECT_ROOT = Path(__file__).parent.parent
STATE_DIR = PROJECT_ROOT / "state"
STATE_DIR.mkdir(parents=True, exist_ok=True)

LIVE_NEXUS_STATE = STATE_DIR / "abcfc_live_nexus.json"
LIVE_NEXUS_LOG = STATE_DIR / "abcfc_live_nexus.jsonl"


# =============================================================================
# LIVE ACTION (Executable, not theoretical)
# =============================================================================

class ActionStatus(Enum):
    PROPOSED = "proposed"       # Generated by nexus
    APPROVED = "approved"       # Passed risk checks
    EXECUTED = "executed"       # Trade placed
    FILLED = "filled"           # Order filled
    REJECTED = "rejected"       # Failed risk check
    CANCELLED = "cancelled"     # User or system cancelled


@dataclass
class LiveAction:
    """
    An executable action with real market data.

    Unlike theoretical Action, this has:
    - Real market/token IDs
    - Actual prices from order book
    - Calculated probabilities
    - Execution status
    """
    # Identity
    action_id: str
    created_at: str

    # Market info (real)
    market_id: str              # Polymarket condition ID
    market_slug: str            # Human readable
    token_id: str               # YES or NO token

    # Trade params (from order book)
    side: str                   # "YES" or "NO"
    size: float                 # Number of shares
    price: float                # Entry price
    limit_price: float          # Max price willing to pay

    # Probability estimate (real, not 50%)
    prob_estimate: float        # Our probability estimate
    market_prob: float          # Market implied probability
    edge: float                 # Our edge (prob_estimate - price)

    # ABCFC bounds (calculated from real data)
    worst_pnl: float            # If wrong
    best_pnl: float             # If right
    expected_pnl: float         # Edge * stake

    # Scoring
    nexus_score: float = 0.0
    risk_adjusted_score: float = 0.0

    # Execution
    status: ActionStatus = ActionStatus.PROPOSED
    order_id: Optional[str] = None
    fill_price: Optional[float] = None
    filled_size: Optional[float] = None

    # Outcome (after resolution)
    outcome: Optional[str] = None  # "won", "lost", "pending"
    realized_pnl: Optional[float] = None

    def to_dict(self) -> Dict:
        return {
            "action_id": self.action_id,
            "created_at": self.created_at,
            "market_slug": self.market_slug,
            "side": self.side,
            "size": self.size,
            "price": self.price,
            "prob_estimate": self.prob_estimate,
            "edge": self.edge,
            "worst_pnl": self.worst_pnl,
            "best_pnl": self.best_pnl,
            "expected_pnl": self.expected_pnl,
            "nexus_score": self.nexus_score,
            "status": self.status.value,
            "outcome": self.outcome,
            "realized_pnl": self.realized_pnl,
        }


# =============================================================================
# LIVE MARKET DATA
# =============================================================================

@dataclass
class LiveMarketData:
    """Real market data for nexus evaluation."""
    market_id: str
    market_slug: str
    question: str

    # Current prices
    yes_price: float
    no_price: float
    mid_price: float
    spread: float

    # Order book depth
    yes_bid_depth: float        # Liquidity at bid
    yes_ask_depth: float        # Liquidity at ask
    no_bid_depth: float
    no_ask_depth: float

    # Volume
    volume_24h: float
    total_volume: float

    # Time
    end_date: Optional[str] = None
    days_to_resolution: float = 30.0

    # Our estimate (from wisdom engine or model)
    prob_estimate: Optional[float] = None

    @property
    def yes_edge(self) -> float:
        """Edge for YES position."""
        if self.prob_estimate is None:
            return 0.0
        return self.prob_estimate - self.yes_price

    @property
    def no_edge(self) -> float:
        """Edge for NO position."""
        if self.prob_estimate is None:
            return 0.0
        return (1 - self.prob_estimate) - self.no_price


# =============================================================================
# ABCFC LIVE NEXUS
# =============================================================================

class ABCFCLiveNexus:
    """
    Live ABCFC Nexus - Connects theory to practice.

    OBSERVE → GENERATE → SIMULATE → DECIDE → EXECUTE → TRACK
    """

    def __init__(self, risk_aversion: float = 0.6, dry_run: bool = True):
        self.risk_aversion = risk_aversion
        self.dry_run = dry_run

        # State
        self.current_positions: List[Dict] = []
        self.market_data: Dict[str, LiveMarketData] = {}
        self.proposed_actions: List[LiveAction] = []
        self.executed_actions: List[LiveAction] = []

        # Polymarket client (lazy load)
        self._client = None

        # Constraints
        self.max_position_size = 100  # Per market
        self.min_edge = 0.05          # 5% minimum edge
        self.max_total_exposure = 500  # Total across all positions

        # Load state
        self._load_state()

    # =========================================================================
    # POLYMARKET CLIENT
    # =========================================================================

    @property
    def client(self):
        """Lazy load Polymarket client."""
        if self._client is None:
            try:
                from py_clob_client.client import ClobClient

                host = "https://clob.polymarket.com"
                key = os.environ.get("POLYMARKET_PRIVATE_KEY",
                    "0x644444ab1d39e9074b01f085a27a4bbf5a8536f411b9b2bea04eb3934f038493")
                chain_id = 137

                self._client = ClobClient(host, key=key, chain_id=chain_id)
                creds = self._client.create_or_derive_api_creds()
                self._client.set_api_creds(creds)
            except Exception as e:
                print(f"Warning: Could not init Polymarket client: {e}")
                self._client = None
        return self._client

    # =========================================================================
    # OBSERVE - Pull real data
    # =========================================================================

    def observe(self) -> Dict:
        """
        Pull real market data and positions.

        Returns current state snapshot.
        """
        self.current_positions = []
        self.market_data = {}

        # Load positions from state
        positions_file = STATE_DIR / "polymarket_live_state.json"
        if positions_file.exists():
            try:
                with open(positions_file) as f:
                    state = json.load(f)
                self.current_positions = state.get("positions", [])
            except:
                pass

        # Try to get live data from client
        if self.client:
            try:
                orders = self.client.get_orders()
                # Process orders into positions...
            except:
                pass

        # Load probability estimates from wisdom engine
        prob_estimates = self._load_probability_estimates()

        # Get market opportunities
        markets = self._get_market_opportunities()

        for market in markets:
            # Get order book
            book_data = self._get_order_book(market.get("token_id", ""))

            # Create LiveMarketData
            market_id = market.get("condition_id", "")
            self.market_data[market_id] = LiveMarketData(
                market_id=market_id,
                market_slug=market.get("slug", ""),
                question=market.get("question", ""),
                yes_price=market.get("yes_price", 0.5),
                no_price=market.get("no_price", 0.5),
                mid_price=(market.get("yes_price", 0.5) + (1 - market.get("no_price", 0.5))) / 2,
                spread=market.get("spread", 0.02),
                yes_bid_depth=book_data.get("yes_bid_depth", 0),
                yes_ask_depth=book_data.get("yes_ask_depth", 0),
                no_bid_depth=book_data.get("no_bid_depth", 0),
                no_ask_depth=book_data.get("no_ask_depth", 0),
                volume_24h=market.get("volume_24h", 0),
                total_volume=market.get("total_volume", 0),
                prob_estimate=prob_estimates.get(market_id),
            )

        return {
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "positions": len(self.current_positions),
            "markets_scanned": len(self.market_data),
            "total_exposure": sum(p.get("size", 0) * p.get("entry_price", 0)
                                  for p in self.current_positions),
        }

    def _load_probability_estimates(self) -> Dict[str, float]:
        """Load probability estimates from human wisdom + machine models."""
        estimates = {}

        # 1. Load human estimates (highest priority)
        human_estimates_file = STATE_DIR / "human_probability_estimates.json"
        if human_estimates_file.exists():
            try:
                with open(human_estimates_file) as f:
                    data = json.load(f)
                estimates.update(data.get("estimates", {}))
            except:
                pass

        # 2. Load from synergy wisdom cache
        synergy_file = STATE_DIR / "human_machine_synergy.json"
        if synergy_file.exists():
            try:
                with open(synergy_file) as f:
                    data = json.load(f)
                for market_id, wisdom in data.get("wisdom_cache", {}).items():
                    if market_id not in estimates:  # Don't override human file
                        estimates[market_id] = wisdom.get("probability")
            except:
                pass

        # 3. Load from wisdom engine (lowest priority)
        try:
            from autonomous.yair_wisdom_engine import YairWisdomEngine
            engine = YairWisdomEngine()
            # This would pull estimates from calibrated predictions
        except:
            pass

        return estimates

    def _get_market_opportunities(self) -> List[Dict]:
        """Get list of market opportunities."""
        opportunities = []

        # 1. Try polymarket-model.json (has analyzed markets with edges)
        model_file = STATE_DIR / "polymarket-model.json"
        if model_file.exists():
            try:
                with open(model_file) as f:
                    data = json.load(f)
                markets = data.get("markets", [])
                for m in markets:
                    opportunities.append({
                        "condition_id": m.get("market_id", ""),
                        "slug": m.get("market_id", ""),
                        "question": m.get("question", ""),
                        "yes_price": m.get("market_price", 0.5),
                        "no_price": 1 - m.get("market_price", 0.5),
                        "spread": m.get("spread_pct", 0.02),
                        "volume_24h": 0,
                        "total_volume": 0,
                        "token_id": "",
                        "fair_price": m.get("fair_price"),
                        "model_edge": m.get("model_edge", 0),
                    })
            except:
                pass

        # 2. Fallback to polymarket knowledge
        if not opportunities:
            knowledge_file = STATE_DIR / "polymarket_knowledge.json"
            if knowledge_file.exists():
                try:
                    with open(knowledge_file) as f:
                        data = json.load(f)
                    opportunities = data.get("markets", [])[:20]
                except:
                    pass

        # 3. If no knowledge, try live API
        if not opportunities and self.client:
            try:
                markets = self.client.get_markets()
                opportunities = markets[:20] if markets else []
            except:
                pass

        return opportunities[:20]  # Top 20

    def _get_order_book(self, token_id: str) -> Dict:
        """Get order book data for a token."""
        if not token_id or not self.client:
            return {
                "yes_bid_depth": 100,
                "yes_ask_depth": 100,
                "no_bid_depth": 100,
                "no_ask_depth": 100,
            }

        try:
            book = self.client.get_order_book(token_id)
            bids = getattr(book, 'bids', []) or []
            asks = getattr(book, 'asks', []) or []

            return {
                "yes_bid_depth": sum(float(b.size) for b in bids[:5]),
                "yes_ask_depth": sum(float(a.size) for a in asks[:5]),
                "no_bid_depth": 100,  # Would need complementary token
                "no_ask_depth": 100,
            }
        except:
            return {
                "yes_bid_depth": 100,
                "yes_ask_depth": 100,
                "no_bid_depth": 100,
                "no_ask_depth": 100,
            }

    # =========================================================================
    # GENERATE - Create executable actions from opportunities
    # =========================================================================

    def generate_actions(self) -> List[LiveAction]:
        """
        Generate executable actions from real market opportunities.

        Only generates actions where:
        1. Edge > min_edge (profitable)
        2. Liquidity sufficient (can execute)
        3. Risk limits allow (position sizing)
        """
        self.proposed_actions = []

        # Calculate current exposure
        current_exposure = sum(
            p.get("size", 0) * p.get("entry_price", 0)
            for p in self.current_positions
        )
        available_capital = self.max_total_exposure - current_exposure

        if available_capital <= 0:
            return []

        for market_id, market in self.market_data.items():
            # Check if we have a probability estimate
            if market.prob_estimate is None:
                # Use market price as probability (no edge)
                continue

            # Check YES edge
            if market.yes_edge >= self.min_edge:
                # Calculate position size (Kelly or fixed)
                size = self._calculate_position_size(
                    edge=market.yes_edge,
                    price=market.yes_price,
                    available=available_capital,
                )

                if size > 0:
                    action = self._create_action(
                        market=market,
                        side="YES",
                        size=size,
                        price=market.yes_price,
                    )
                    self.proposed_actions.append(action)

            # Check NO edge
            if market.no_edge >= self.min_edge:
                size = self._calculate_position_size(
                    edge=market.no_edge,
                    price=market.no_price,
                    available=available_capital,
                )

                if size > 0:
                    action = self._create_action(
                        market=market,
                        side="NO",
                        size=size,
                        price=market.no_price,
                    )
                    self.proposed_actions.append(action)

        # Sort by expected P&L
        self.proposed_actions.sort(key=lambda a: a.expected_pnl, reverse=True)

        return self.proposed_actions

    def _calculate_position_size(self, edge: float, price: float,
                                  available: float) -> float:
        """Calculate position size using fractional Kelly."""
        if edge <= 0 or price <= 0 or price >= 1:
            return 0

        # Kelly fraction: edge / odds
        # For binary: f = (p * b - q) / b where b = (1-price)/price
        prob = price + edge
        b = (1 - price) / price

        kelly = (prob * b - (1 - prob)) / b if b > 0 else 0
        kelly = max(0, min(kelly, 0.25))  # Cap at 25% Kelly

        # Half Kelly for safety
        kelly *= 0.5

        # Size in dollars
        size = available * kelly

        # Cap at max position
        size = min(size, self.max_position_size)

        return round(size, 2)

    def _create_action(self, market: LiveMarketData, side: str,
                       size: float, price: float) -> LiveAction:
        """Create a LiveAction from market data."""
        # Calculate P&L bounds
        if side == "YES":
            worst_pnl = -size * price           # Lose entire stake
            best_pnl = size * (1 - price)       # Win (1 - price) per share
            expected_pnl = size * market.yes_edge
            prob = market.prob_estimate
        else:
            worst_pnl = -size * price
            best_pnl = size * (1 - price)
            expected_pnl = size * market.no_edge
            prob = 1 - market.prob_estimate

        # Score using ABCFC scoring
        score = self._score_action(worst_pnl, best_pnl, expected_pnl)

        return LiveAction(
            action_id=f"{market.market_slug}_{side}_{datetime.now().timestamp():.0f}",
            created_at=datetime.now(timezone.utc).isoformat(),
            market_id=market.market_id,
            market_slug=market.market_slug,
            token_id="",  # Would need actual token ID
            side=side,
            size=size,
            price=price,
            limit_price=price * 1.02,  # 2% slippage tolerance
            prob_estimate=prob,
            market_prob=market.yes_price if side == "YES" else market.no_price,
            edge=market.yes_edge if side == "YES" else market.no_edge,
            worst_pnl=worst_pnl,
            best_pnl=best_pnl,
            expected_pnl=expected_pnl,
            nexus_score=score,
            risk_adjusted_score=score,
        )

    def _score_action(self, worst: float, best: float, expected: float) -> float:
        """Score action using ABCFC methodology."""
        range_val = max(abs(best), abs(worst), 1)

        expected_norm = expected / range_val
        downside_norm = worst / range_val

        # Risk-adjusted score
        score = expected_norm * (1 - self.risk_aversion)
        score += downside_norm * self.risk_aversion

        return score * 100  # Scale to reasonable range

    # =========================================================================
    # SIMULATE - Calculate impacts with real probabilities
    # =========================================================================

    def simulate_portfolio_impact(self, action: LiveAction) -> Dict:
        """
        Simulate how action affects total portfolio ABCFC.

        Uses real data, not theoretical 50% assumptions.
        """
        # Current portfolio bounds
        current_worst = sum(p.get("worst_pnl", 0) for p in self.current_positions)
        current_best = sum(p.get("best_pnl", 0) for p in self.current_positions)
        current_expected = sum(p.get("expected_pnl", 0) for p in self.current_positions)

        # New bounds after action
        new_worst = current_worst + action.worst_pnl
        new_best = current_best + action.best_pnl
        new_expected = current_expected + action.expected_pnl

        return {
            "current": {
                "worst": current_worst,
                "best": current_best,
                "expected": current_expected,
            },
            "after": {
                "worst": new_worst,
                "best": new_best,
                "expected": new_expected,
            },
            "delta": {
                "worst": action.worst_pnl,
                "best": action.best_pnl,
                "expected": action.expected_pnl,
            },
            "score": action.nexus_score,
        }

    # =========================================================================
    # DECIDE - Select best actions
    # =========================================================================

    def decide(self, max_actions: int = 3) -> List[LiveAction]:
        """
        Select best actions from proposed set.

        Considers:
        - Individual action scores
        - Portfolio diversification
        - Risk limits
        """
        if not self.proposed_actions:
            return []

        # Filter by risk checks
        approved = []
        remaining_capital = self.max_total_exposure

        for action in self.proposed_actions:
            # Check position limit
            if action.size * action.price > remaining_capital:
                action.status = ActionStatus.REJECTED
                continue

            # Check edge requirement
            if action.edge < self.min_edge:
                action.status = ActionStatus.REJECTED
                continue

            action.status = ActionStatus.APPROVED
            approved.append(action)
            remaining_capital -= action.size * action.price

            if len(approved) >= max_actions:
                break

        return approved

    # =========================================================================
    # EXECUTE - Place trades
    # =========================================================================

    def execute(self, actions: List[LiveAction] = None) -> List[Dict]:
        """
        Execute approved actions.

        In dry_run mode, logs but doesn't place orders.
        """
        if actions is None:
            actions = [a for a in self.proposed_actions if a.status == ActionStatus.APPROVED]

        results = []

        for action in actions:
            if self.dry_run:
                result = {
                    "action_id": action.action_id,
                    "status": "DRY_RUN",
                    "market": action.market_slug,
                    "side": action.side,
                    "size": action.size,
                    "price": action.price,
                    "expected_pnl": action.expected_pnl,
                    "executed": False,
                }
            else:
                # Real execution
                result = self._execute_trade(action)

            results.append(result)
            self._log_action(action, result)

        return results

    def _execute_trade(self, action: LiveAction) -> Dict:
        """
        Execute actual trade via Polymarket API.
        INTEGRAFIX: Wired to credential_loader and py_clob_client.
        """
        if not self.client:
            return {
                "action_id": action.action_id,
                "status": "ERROR",
                "error": "No Polymarket client",
                "executed": False,
            }

        try:
            # INTEGRAFIX: Execute actual order
            from py_clob_client.clob_types import OrderArgs
            from py_clob_client.order_builder.constants import BUY, SELL

            token_id = action.token_id or action.market_slug
            side_const = BUY if action.side == "YES" else SELL

            order_args = OrderArgs(
                token_id=token_id,
                price=action.price,
                size=action.size,
                side=side_const
            )

            signed_order = self.client.create_order(order_args)
            result = self.client.submit_legacy_order(signed_order)

            order_id = result.get("orderID") or result.get("id") if result else None

            if order_id or result:
                action.status = ActionStatus.EXECUTED
                return {
                    "action_id": action.action_id,
                    "status": "EXECUTED",
                    "market": action.market_slug,
                    "side": action.side,
                    "size": action.size,
                    "order_id": str(order_id or result)[:50],
                    "executed": True,
                }
            else:
                action.status = ActionStatus.REJECTED
                return {
                    "action_id": action.action_id,
                    "status": "ERROR",
                    "error": "No order_id returned",
                    "executed": False,
                }

        except Exception as e:
            action.status = ActionStatus.REJECTED

            return {
                "action_id": action.action_id,
                "status": "ERROR",
                "error": str(e),
                "executed": False,
            }

    # =========================================================================
    # TRACK - Record outcomes and learn
    # =========================================================================

    def track_outcome(self, action_id: str, outcome: str, realized_pnl: float) -> Dict:
        """
        Record outcome of executed action.

        Feeds back to learning system for calibration.
        """
        # Find action
        action = None
        for a in self.executed_actions:
            if a.action_id == action_id:
                action = a
                break

        if not action:
            return {"error": f"Action {action_id} not found"}

        # Record outcome
        action.outcome = outcome
        action.realized_pnl = realized_pnl

        # Update state
        self._save_state()

        # Feed to learning
        self._feed_to_learning(action)

        return {
            "action_id": action_id,
            "outcome": outcome,
            "realized_pnl": realized_pnl,
            "expected_pnl": action.expected_pnl,
            "edge_realized": realized_pnl - action.expected_pnl,
        }

    def _feed_to_learning(self, action: LiveAction):
        """Feed outcome to learning system for calibration."""
        try:
            from integrafix.goals_effects_bridge import GoalsEffectsBridge, EffectType
            bridge = GoalsEffectsBridge()
            bridge.record_effect(
                name=f"Trade: {action.market_slug} {action.side}",
                description=f"Outcome: {action.outcome}, P&L: ${action.realized_pnl:.2f}",
                effect_type=EffectType.OUTCOME,
                value=action.realized_pnl,
                value_type="currency",
            )
        except:
            pass

        try:
            from autonomous.probability_calibrator import ProbabilityCalibrator
            calibrator = ProbabilityCalibrator()
            calibrator.record_prediction(
                prediction_id=action.action_id,
                predicted_prob=action.prob_estimate,
                actual_outcome=1 if action.outcome == "won" else 0,
            )
        except:
            pass

    # =========================================================================
    # FULL CYCLE
    # =========================================================================

    def run_cycle(self) -> Dict:
        """
        Run complete OBSERVE → GENERATE → DECIDE → EXECUTE cycle.
        """
        # 1. Observe
        obs = self.observe()

        # 2. Generate
        actions = self.generate_actions()

        # 3. Decide
        approved = self.decide()

        # 4. Execute
        results = self.execute(approved)

        # 5. Save state
        self._save_state()

        return {
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "dry_run": self.dry_run,
            "observed": obs,
            "actions_generated": len(actions),
            "actions_approved": len(approved),
            "execution_results": results,
        }

    # =========================================================================
    # STATE MANAGEMENT
    # =========================================================================

    def _load_state(self):
        """Load state from disk."""
        if LIVE_NEXUS_STATE.exists():
            try:
                with open(LIVE_NEXUS_STATE) as f:
                    data = json.load(f)
                # Restore executed actions for tracking
            except:
                pass

    def _save_state(self):
        """Save state to disk."""
        state = {
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "risk_aversion": self.risk_aversion,
            "dry_run": self.dry_run,
            "proposed_actions": len(self.proposed_actions),
            "executed_actions": len(self.executed_actions),
            "current_exposure": sum(p.get("size", 0) * p.get("entry_price", 0)
                                    for p in self.current_positions),
        }
        with open(LIVE_NEXUS_STATE, 'w') as f:
            json.dump(state, f, indent=2)

    def _log_action(self, action: LiveAction, result: Dict):
        """Log action to file."""
        entry = {
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "action": action.to_dict(),
            "result": result,
        }
        with open(LIVE_NEXUS_LOG, 'a') as f:
            f.write(json.dumps(entry) + '\n')

    # =========================================================================
    # REPORTING
    # =========================================================================

    def print_status(self):
        """Print current nexus status."""
        print("=" * 70)
        print("ABCFC LIVE NEXUS STATUS")
        print(f"Generated: {datetime.now(timezone.utc).isoformat()}")
        print("=" * 70)

        print(f"\n>>> MODE: {'DRY RUN' if self.dry_run else 'LIVE'}")
        print(f"    Risk Aversion: {self.risk_aversion}")
        print(f"    Min Edge: {self.min_edge:.0%}")
        print(f"    Max Position: ${self.max_position_size}")

        print(f"\n>>> POSITIONS")
        print(f"    Current: {len(self.current_positions)}")
        exposure = sum(p.get("size", 0) * p.get("entry_price", 0)
                       for p in self.current_positions)
        print(f"    Exposure: ${exposure:.2f} / ${self.max_total_exposure}")

        print(f"\n>>> MARKETS SCANNED")
        print(f"    Markets: {len(self.market_data)}")
        with_edge = [m for m in self.market_data.values()
                     if m.prob_estimate and (abs(m.yes_edge) > self.min_edge or
                                              abs(m.no_edge) > self.min_edge)]
        print(f"    With Edge: {len(with_edge)}")

        print(f"\n>>> PROPOSED ACTIONS")
        print(f"    Total: {len(self.proposed_actions)}")
        approved = [a for a in self.proposed_actions if a.status == ActionStatus.APPROVED]
        print(f"    Approved: {len(approved)}")

        if approved:
            print(f"\n>>> TOP ACTIONS")
            for i, a in enumerate(approved[:3], 1):
                print(f"    {i}. {a.market_slug[:30]}")
                print(f"       {a.side} @ ${a.price:.2f} x {a.size:.0f}")
                print(f"       Edge: {a.edge:.1%} | E[P&L]: ${a.expected_pnl:.2f}")

        print("\n" + "=" * 70)

    def get_nexus_cloud_data(self) -> Dict:
        """Get nexus cloud data for visualization."""
        return {
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "mode": "DRY_RUN" if self.dry_run else "LIVE",
            "markets": len(self.market_data),
            "actions": [a.to_dict() for a in self.proposed_actions[:10]],
            "approved": [a.to_dict() for a in self.proposed_actions
                        if a.status == ActionStatus.APPROVED],
            "cloud_bounds": {
                "worst_possible": sum(a.worst_pnl for a in self.proposed_actions[:5]),
                "best_possible": sum(a.best_pnl for a in self.proposed_actions[:5]),
                "expected": sum(a.expected_pnl for a in self.proposed_actions[:5]),
            }
        }


# =============================================================================
# CLI
# =============================================================================

def main():
    import argparse

    parser = argparse.ArgumentParser(description="ABCFC Live Nexus")
    parser.add_argument("command", choices=[
        "status", "observe", "generate", "decide", "execute", "cycle"
    ], default="status", nargs="?")
    parser.add_argument("--risk", type=float, default=0.6, help="Risk aversion (0-1)")
    parser.add_argument("--live", action="store_true", help="Execute real trades")
    parser.add_argument("--min-edge", type=float, default=0.05, help="Minimum edge")
    args = parser.parse_args()

    nexus = ABCFCLiveNexus(
        risk_aversion=args.risk,
        dry_run=not args.live,
    )
    nexus.min_edge = args.min_edge

    if args.command == "status":
        nexus.observe()
        nexus.generate_actions()
        nexus.decide()
        nexus.print_status()

    elif args.command == "observe":
        result = nexus.observe()
        print(json.dumps(result, indent=2))

    elif args.command == "generate":
        nexus.observe()
        actions = nexus.generate_actions()
        print(f"Generated {len(actions)} actions:")
        for a in actions[:5]:
            print(f"  {a.market_slug[:30]} {a.side} @ {a.price:.2f} E={a.expected_pnl:.2f}")

    elif args.command == "decide":
        nexus.observe()
        nexus.generate_actions()
        approved = nexus.decide()
        print(f"Approved {len(approved)} actions:")
        for a in approved:
            print(f"  {a.market_slug[:30]} {a.side} @ {a.price:.2f} E={a.expected_pnl:.2f}")

    elif args.command == "execute":
        nexus.observe()
        nexus.generate_actions()
        approved = nexus.decide()
        results = nexus.execute(approved)
        print(json.dumps(results, indent=2))

    elif args.command == "cycle":
        result = nexus.run_cycle()
        print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
