#!/bin/bash
# Trading Activation Script - Auto-generated by self_modification.py
# Activates trading when balance reaches $50

BALANCE=$(python3 -c "
import json
from pathlib import Path
state = Path('/root/hands-off-engine/state/capital_state.json')
if state.exists():
    data = json.load(open(state))
    print(data.get('balance', 0))
else:
    print(0)
")

if (( $(echo "$BALANCE >= 50" | bc -l) )); then
    echo "Balance $BALANCE >= 50 - TRADING ENABLED"
    python3 /root/hands-off-engine/trading/polymarket_trader.py
else
    echo "Balance $BALANCE < 50 - waiting for threshold"
fi
