#!/usr/bin/env python3
"""Improvement Dispatcher — closes the autonomous self-improvement loop.

Reads improvement_state.json (generated by self_improvement.py), filters to
actionable items, and dispatches them as task_assignments on the canonical
bus. Node 1 consumes them, executes, and results feed back into the learning
loop. This is the Factory candidate → dispatch gap being closed.

Safety: only dispatches safe/medium actions automatically. High-priority
reliability/security items are quarantined for operator approval.
"""
import json
import uuid
from pathlib import Path
from datetime import datetime, timezone

ROOT = Path(__file__).resolve().parent.parent
STATE = ROOT / "state"
BUS = ROOT / "ai" / "coordination" / "messages.jsonl"
IMPROVEMENT_STATE = STATE / "improvement_state.json"
DISPATCH_STATE = STATE / "dispatch_state.json"

# Categories auto-dispatched (safe, bounded, reversible)
AUTO_DISPATCH = {"maintenance", "usability", "documentation", "quality"}
# Categories quarantined for approval
QUARANTINE = {"reliability", "security", "expansion"}


def load_improvements():
    try:
        return json.loads(IMPROVEMENT_STATE.read_text()).get("improvements", [])
    except Exception:
        return []


def load_dispatched():
    if DISPATCH_STATE.exists():
        try:
            return set(json.loads(DISPATCH_STATE.read_text()).get("dispatched_ids", []))
        except Exception:
            pass
    return set()


def save_dispatched(dispatched):
    DISPATCH_STATE.write_text(json.dumps({
        "dispatched_ids": sorted(dispatched),
        "updated_at": datetime.now(timezone.utc).isoformat(),
    }, indent=2) + "\n")


def dispatch():
    """Dispatch safe improvements to the bus as task_assignments."""
    improvements = load_improvements()
    dispatched = load_dispatched()
    results = {"dispatched": [], "quarantined": [], "skipped": []}
    
    for imp in improvements:
        imp_id = imp.get("id", "")
        if not imp_id or imp_id in dispatched:
            continue
        category = imp.get("category", "")
        title = imp.get("title", "")
        
        if category in QUARANTINE:
            results["quarantined"].append({"id": imp_id, "title": title, "category": category})
            continue
        
        if category not in AUTO_DISPATCH:
            results["skipped"].append({"id": imp_id, "title": title, "category": category})
            continue
        
        # Dispatch as a task on the canonical bus
        task = {
            "from": "factory",
            "to": "anyclaw",
            "type": "task_assignment",
            "message": f"Auto-improvement task: {title}. {imp.get('description', '')}",
            "msg_id": f"improve-{imp_id[:8]}",
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "priority": 6,
            "context": {
                "task_id": f"improve-{imp_id[:8]}",
                "action": "system_status",  # safe bounded action
                "params": {"improvement": title, "description": imp.get("description", "")},
                "reply_to": "auto_improve",
            },
        }
        try:
            with open(BUS, "a") as f:
                f.write(json.dumps(task) + "\n")
            dispatched.add(imp_id)
            results["dispatched"].append({"id": imp_id, "title": title, "category": category})
        except Exception as e:
            results["skipped"].append({"id": imp_id, "title": title, "error": str(e)})
    
    save_dispatched(dispatched)
    
    print(f"Dispatcher: {len(results['dispatched'])} dispatched, "
          f"{len(results['quarantined'])} quarantined, {len(results['skipped'])} skipped")
    for r in results["dispatched"]:
        print(f"  ➡️  {r['title']}")
    for r in results["quarantined"]:
        print(f"  🔒 {r['title']} (needs approval)")
    
    return results


if __name__ == "__main__":
    dispatch()
