#!/bin/bash
# GitHub Token Setup - Interactive Script
# Sets up GITHUB_TOKEN for authenticated API access (5000 req/hour vs 60 unauthenticated)

set -e

# Helper function to parse JSON rate limit response
parse_rate_limit() {
    local json="$1"
    local field="$2"
    python3 -c "
import json
import sys
try:
    data = json.loads(sys.stdin.read())
    print(data.get('resources', {}).get('core', {}).get('$field', 0))
except:
    print(0)
" <<< "$json" 2>/dev/null || echo "0"
}

echo "=================================="
echo "🔑 GITHUB TOKEN SETUP"
echo "=================================="
echo ""
echo "This script configures GITHUB_TOKEN for authenticated GitHub API access."
echo "Unauthenticated: 60 requests/hour"
echo "Authenticated:   5,000 requests/hour"
echo ""

# Detect environment (Termux or Linux)
if [ -d "/data/data/com.termux" ]; then
    ENV_TYPE="termux"
    CONFIG_DIR="$HOME/.config/github"
    SHELL_RC="$HOME/.bashrc"
else
    ENV_TYPE="linux"
    CONFIG_DIR="$HOME/.config/github"
    # Detect shell RC file
    if [ -n "$ZSH_VERSION" ]; then
        SHELL_RC="$HOME/.zshrc"
    else
        SHELL_RC="$HOME/.bashrc"
    fi
fi

echo "Detected environment: $ENV_TYPE"
echo "Config will be saved to: $CONFIG_DIR/env"
echo "Shell RC: $SHELL_RC"
echo ""

# Check if already configured
if [ -n "$GITHUB_TOKEN" ]; then
    echo "✅ GITHUB_TOKEN is already set!"
    echo ""
    echo "Current token: ${GITHUB_TOKEN:0:10}..."
    echo ""
    
    # Test current token
    echo "Testing current token..."
    RATE_INFO=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
        -H "Accept: application/vnd.github+json" \
        "https://api.github.com/rate_limit" 2>/dev/null || echo '{}')
    
    LIMIT=$(parse_rate_limit "$RATE_INFO" "limit")
    REMAINING=$(parse_rate_limit "$RATE_INFO" "remaining")
    
    if [ "$LIMIT" = "5000" ]; then
        echo "✅ Token is valid! Rate limit: $REMAINING/$LIMIT remaining"
        echo ""
        read -p "Do you want to reconfigure? (y/N): " reconfigure
        if [ "$reconfigure" != "y" ] && [ "$reconfigure" != "Y" ]; then
            echo "Keeping existing configuration."
            exit 0
        fi
    else
        echo "⚠️  Current token may be invalid or expired."
        echo "   Rate limit shows: $LIMIT (expected 5000 for authenticated)"
    fi
fi

echo ""
echo "=================================="
echo "STEP 1: Create GitHub Token"
echo "=================================="
echo ""
echo "1. Go to: https://github.com/settings/tokens"
echo "2. Click 'Generate new token' -> 'Generate new token (classic)'"
echo "3. Settings:"
echo "   - Note: 'Hands-Off Engine'"
echo "   - Expiration: 90 days or No expiration"
echo "   - Scopes: Select 'repo' (full control of private repos)"
echo "4. Click 'Generate token'"
echo "5. Copy the token (starts with 'ghp_' or 'github_pat_')"
echo ""
read -p "Press ENTER when you have your token ready..."
echo ""
read -sp "Paste your GitHub token here (hidden): " GITHUB_TOKEN_INPUT
echo ""

if [ -z "$GITHUB_TOKEN_INPUT" ]; then
    echo "❌ No token provided. Exiting."
    exit 1
fi

echo ""
echo "✅ Token received"
echo ""

echo "=================================="
echo "STEP 2: Validating Token"
echo "=================================="
echo ""
echo "Testing token with GitHub API..."

RATE_INFO=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN_INPUT" \
    -H "Accept: application/vnd.github+json" \
    "https://api.github.com/rate_limit" 2>/dev/null || echo '{}')

LIMIT=$(parse_rate_limit "$RATE_INFO" "limit")
REMAINING=$(parse_rate_limit "$RATE_INFO" "remaining")

if [ "$LIMIT" = "5000" ]; then
    echo "✅ Token is valid!"
    echo "   Rate limit: $REMAINING/$LIMIT remaining"
else
    echo "⚠️  Token validation issue."
    echo "   Rate limit: $LIMIT (expected 5000 for authenticated)"
    echo ""
    read -p "Continue anyway? (y/N): " continue_anyway
    if [ "$continue_anyway" != "y" ] && [ "$continue_anyway" != "Y" ]; then
        echo "Exiting. Please verify your token."
        exit 1
    fi
fi

echo ""
echo "=================================="
echo "STEP 3: Saving Configuration"
echo "=================================="
echo ""

# Create config directory with secure permissions
mkdir -p "$CONFIG_DIR"
chmod 700 "$CONFIG_DIR"

# Save token to config file with secure permissions
ENV_FILE="$CONFIG_DIR/env"
echo "# GitHub Token Configuration" > "$ENV_FILE"
echo "# Generated by setup_github_token.sh on $(date)" >> "$ENV_FILE"
echo "export GITHUB_TOKEN=\"$GITHUB_TOKEN_INPUT\"" >> "$ENV_FILE"
chmod 600 "$ENV_FILE"

echo "✅ Token saved to: $ENV_FILE"

# Add source line to shell RC if not present
SOURCE_LINE="source \"$ENV_FILE\""
if ! grep -qF "$ENV_FILE" "$SHELL_RC" 2>/dev/null; then
    echo "" >> "$SHELL_RC"
    echo "# GitHub Token (Hands-Off Engine)" >> "$SHELL_RC"
    echo "[ -f \"$ENV_FILE\" ] && source \"$ENV_FILE\"" >> "$SHELL_RC"
    echo "✅ Added source line to: $SHELL_RC"
else
    echo "✅ Source line already exists in: $SHELL_RC"
fi

# Export for current session
export GITHUB_TOKEN="$GITHUB_TOKEN_INPUT"

echo ""
echo "=================================="
echo "STEP 4: Final Verification"
echo "=================================="
echo ""

# Run the status script if it exists
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [ -f "$SCRIPT_DIR/github_ratelimit_status.py" ]; then
    echo "Running rate limit status check..."
    echo ""
    python3 "$SCRIPT_DIR/github_ratelimit_status.py" 2>/dev/null || {
        echo "Rate limit check script not available"
    }
else
    echo "Rate limit: $REMAINING/$LIMIT remaining"
fi

echo ""
echo "=================================="
echo "✅ SETUP COMPLETE!"
echo "=================================="
echo ""
echo "Your GitHub token is now configured."
echo ""
echo "To apply changes in current terminal:"
echo "  source $ENV_FILE"
echo ""
echo "Or restart your terminal."
echo ""
echo "To verify setup anytime:"
echo "  python3 $SCRIPT_DIR/github_ratelimit_status.py"
echo ""
