#!/usr/bin/env python3
"""Task Request — AnyClaw → Factory request channel.

AnyClaw proactively requests work through the governed CommHub boundary.
The canonical coordination bus remains the only transport/source of truth;
local request state is intentionally not maintained here.
"""
from pathlib import Path

ALLOWED_TYPES = {"work_request", "question", "status_probe"}


def _repo_root(repo_root=None):
    return Path(repo_root) if repo_root is not None else Path(__file__).resolve().parent.parent


def request_id(request_type, message):
    """Compatibility helper; identity is ultimately generated by CommHub."""
    from datetime import datetime, timezone
    import hashlib
    raw = f"{request_type}|{message}|{datetime.now(timezone.utc).isoformat()}"
    return "req-" + hashlib.sha256(raw.encode()).hexdigest()[:16]


def send_request(request_type, message, params=None, repo_root=None):
    """Send a bounded AnyClaw request through the governed CommHub boundary."""
    if request_type not in ALLOWED_TYPES:
        raise ValueError(f"Invalid request type: {request_type}. Allowed: {ALLOWED_TYPES}")
    text = str(message).strip()
    if not text or len(text) > 2048:
        raise ValueError("message must be 1-2048 characters")

    from scripts.comm_hub import CommHub

    payload = {
        "type": "task_request",
        "message": text,
        "msg_id": request_id(request_type, text),
        "context": {
            "request_type": request_type,
            "params": params or {},
        },
    }
    result = CommHub(repo_root=_repo_root(repo_root)).receive(
        "anyclaw",
        "task_request",
        payload,
        channel="messages_jsonl",
    )
    return result


def request_work(message="Ready for new tasks", repo_root=None):
    return send_request("work_request", message, repo_root=repo_root)


def ask_question(question, context=None, repo_root=None):
    return send_request("question", question, params=context or {}, repo_root=repo_root)


def probe_status(repo_root=None):
    return send_request("status_probe", "Requesting system status update", repo_root=repo_root)


if __name__ == "__main__":
    import sys
    if len(sys.argv) < 2:
        print("Usage: python3 task_request.py work|question|status [message]")
    elif sys.argv[1] == "work":
        request_work(" ".join(sys.argv[2:]) if len(sys.argv) > 2 else "Ready for new tasks")
    elif sys.argv[1] == "question":
        ask_question(" ".join(sys.argv[2:]) if len(sys.argv) > 2 else "What is the next priority?")
    elif sys.argv[1] == "status":
        probe_status()
