#!/usr/bin/env python3
"""
INTELLIGENT ALPHA ENGINE - The Brain That Makes Millions
=========================================================

This module unifies ALL AI infrastructure for intelligent trading:
- Real-time Polymarket data via API
- LLM analysis via AI Nexus (ChatGPT + Claude)
- Consensus engine for multi-model agreement
- Reasoning quality scoring
- Smart order routing (limit vs market)
- Edge detection and position sizing

This is the UNIFIED system that uses everything we've built.
"""

import json
import os
import sys
import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional, Tuple, Any
from dataclasses import dataclass, field

# Add parent to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from executor.polymarket_api import PolymarketAPI, Market, fetch_tradeable_markets
from llm.consensus_engine import build_consensus
from llm.reasoning_booster import score_reasoning, boost_if_needed

LOG = logging.getLogger(__name__)

# Try to import AI Nexus providers
try:
    from ai_nexus.provider_openai import call_chatgpt
    HAS_CHATGPT = True
except ImportError:
    HAS_CHATGPT = False
    LOG.warning("ChatGPT provider not available")

try:
    from ai_nexus.provider_claude import call_claude
    HAS_CLAUDE = True
except ImportError:
    HAS_CLAUDE = False
    LOG.warning("Claude provider not available")


@dataclass
class IntelligentSignal:
    """A signal generated by the intelligent alpha engine"""
    market_id: str
    token_id: str
    question: str
    side: str  # YES or NO

    # AI-derived values
    fair_probability: float  # Model's estimate of true probability
    market_price: float  # Current market price
    edge: float  # fair_probability - market_price (or vice versa for NO)
    confidence: str  # low, medium, high

    # Reasoning from AI
    reasoning: str
    reasoning_quality: int  # 0-100

    # Consensus data
    num_analyses: int
    disagreement_detected: bool

    # Market microstructure
    spread_bps: float
    liquidity: float
    volume_24h: float

    # Order strategy
    order_type: str  # "limit" or "market"
    limit_price: Optional[float] = None
    urgency: str = "normal"  # low, normal, high

    # Sizing
    recommended_size_usd: float = 0.0
    kelly_fraction: float = 0.0

    def to_dict(self) -> Dict:
        return {
            "market_id": self.market_id,
            "token_id": self.token_id,
            "question": self.question,
            "side": self.side,
            "fair_probability": self.fair_probability,
            "market_price": self.market_price,
            "edge": self.edge,
            "confidence": self.confidence,
            "reasoning": self.reasoning,
            "reasoning_quality": self.reasoning_quality,
            "num_analyses": self.num_analyses,
            "disagreement_detected": self.disagreement_detected,
            "spread_bps": self.spread_bps,
            "liquidity": self.liquidity,
            "volume_24h": self.volume_24h,
            "order_type": self.order_type,
            "limit_price": self.limit_price,
            "urgency": self.urgency,
            "recommended_size_usd": self.recommended_size_usd,
            "kelly_fraction": self.kelly_fraction,
        }


class IntelligentAlphaEngine:
    """
    The unified intelligent alpha engine.

    Combines:
    - Real-time Polymarket data
    - Multi-LLM analysis (ChatGPT + Claude)
    - Consensus building
    - Reasoning quality scoring
    - Smart order routing
    """

    def __init__(
        self,
        bankroll: float = 10000.0,
        max_position_pct: float = 0.05,  # 5% max per position
        min_edge: float = 0.05,  # 5% minimum edge
        min_confidence: str = "medium",
        use_chatgpt: bool = True,
        use_claude: bool = True,
    ):
        self.bankroll = bankroll
        self.max_position_pct = max_position_pct
        self.min_edge = min_edge
        self.min_confidence = min_confidence
        self.use_chatgpt = use_chatgpt and HAS_CHATGPT
        self.use_claude = use_claude and HAS_CLAUDE

        self.api = PolymarketAPI()

        LOG.info(f"IntelligentAlphaEngine initialized: bankroll=${bankroll}, ChatGPT={self.use_chatgpt}, Claude={self.use_claude}")

    def fetch_live_markets(self, limit: int = 30) -> List[Market]:
        """Fetch live tradeable markets from Polymarket"""
        LOG.info("Fetching live markets from Polymarket...")

        # Try the working fetch approach first (via /events endpoint)
        markets = self._fetch_via_events(limit)

        if not markets:
            # Fallback to local fresh markets file
            markets = self._load_from_fresh_markets(limit)

        if not markets:
            # Last resort: API class method
            markets = self.api.get_active_markets(
                limit=limit,
                min_volume_24h=1000,
                min_liquidity=5000,
                exclude_restricted=True,
                exclude_sports=False,
            )

        # Enrich with order book data
        for market in markets:
            try:
                self.api.enrich_market_with_orderbook(market)
            except Exception as e:
                LOG.warning(f"Failed to enrich {market.slug}: {e}")

        LOG.info(f"Fetched {len(markets)} live markets")
        return markets

    def _load_from_fresh_markets(self, limit: int = 30) -> List[Market]:
        """Load markets from state/fresh_polymarket_markets.json"""
        fresh_path = Path(__file__).parent.parent / "state" / "fresh_polymarket_markets.json"
        if not fresh_path.exists():
            LOG.warning(f"Fresh markets file not found: {fresh_path}")
            return []

        try:
            with open(fresh_path) as f:
                data = json.load(f)
        except Exception as e:
            LOG.warning(f"Failed to load fresh markets: {e}")
            return []

        markets = []
        for m in data.get("markets", []):
            if m.get("closed", False):
                continue
            # Note: Don't filter on restricted - Polymarket marks many markets
            # as restricted for certain regions, but they're still tradeable
            if m.get("liquidity", 0) < 5000:
                continue

            # Get token IDs
            token_id = m.get("token_id", "")
            market = Market(
                condition_id=m.get("condition_id", ""),
                token_id_yes=token_id,
                token_id_no="",  # Not in compact format
                slug=m.get("slug", ""),
                question=m.get("question", ""),
                last_price=m.get("yes_price"),
                volume_24h=m.get("volume_24h", 0),
                liquidity=m.get("liquidity", 0),
                active=m.get("active", True),
                closed=m.get("closed", False),
                restricted=m.get("restricted", False),
                end_date=m.get("end_date"),
                category=m.get("category", "unknown"),
            )
            markets.append(market)
            if len(markets) >= limit:
                break

        LOG.info(f"Loaded {len(markets)} markets from fresh_polymarket_markets.json")
        return markets

    def _fetch_via_events(self, limit: int = 30) -> List[Market]:
        """
        Fetch markets via /events endpoint (more reliable than /markets).
        """
        import requests

        url = "https://gamma-api.polymarket.com/events"
        params = {"closed": "false", "limit": limit * 2, "active": "true"}

        try:
            resp = requests.get(url, params=params, timeout=30)
            resp.raise_for_status()
            events = resp.json()
        except Exception as e:
            LOG.warning(f"Events endpoint fetch failed: {e}")
            return []

        markets = []
        for event in events:
            for m in event.get("markets", []):
                if m.get("closed", False):
                    continue

                # Parse token IDs
                clob_ids = m.get("clobTokenIds")
                if not clob_ids:
                    continue
                try:
                    if isinstance(clob_ids, str):
                        token_ids = json.loads(clob_ids)
                    else:
                        token_ids = clob_ids
                    if len(token_ids) < 2:
                        continue
                except (json.JSONDecodeError, TypeError):
                    continue

                # Parse prices
                outcome_prices = m.get("outcomePrices")
                last_price = None
                if outcome_prices:
                    try:
                        if isinstance(outcome_prices, str):
                            prices = json.loads(outcome_prices)
                        else:
                            prices = outcome_prices
                        if prices:
                            last_price = float(prices[0])
                    except (json.JSONDecodeError, TypeError, ValueError):
                        pass

                volume_24h = float(m.get("volume24hr", 0) or 0)
                liquidity = float(m.get("liquidityNum", 0) or 0)

                # Filter: require minimum liquidity
                if liquidity < 5000:
                    continue

                market = Market(
                    condition_id=m.get("conditionId", ""),
                    token_id_yes=token_ids[0],
                    token_id_no=token_ids[1] if len(token_ids) > 1 else "",
                    slug=m.get("slug", ""),
                    question=m.get("question", ""),
                    last_price=last_price,
                    volume_24h=volume_24h,
                    liquidity=liquidity,
                    active=m.get("active", True),
                    closed=m.get("closed", False),
                    restricted=m.get("restricted", False),
                    end_date=m.get("endDate"),
                    category=m.get("category", "unknown"),
                )
                markets.append(market)

                if len(markets) >= limit:
                    break

            if len(markets) >= limit:
                break

        return markets

    def analyze_market_with_ai(self, market: Market) -> List[Dict]:
        """
        Analyze a market using multiple AI models.

        Returns list of analysis dicts for consensus building.
        """
        analyses = []

        from datetime import datetime
        today = datetime.now().strftime("%Y-%m-%d")

        prompt = f"""Analyze this Polymarket prediction market:

TODAY'S DATE: {today}

Question: {market.question}
Current YES Price: {market.last_price or market.mid_price or 0.5:.2f}
Category: {market.category}
End Date: {market.end_date or 'Unknown'}
24h Volume: ${market.volume_24h:,.0f}
Liquidity: ${market.liquidity:,.0f}

CRITICAL FACTS FOR 2025 FED RATE DECISIONS:
- Fed has cut rates 2 times in 2025 so far (Sept and Oct, 25bps each)
- Current Fed rate: 3.75%-4.00%
- Only ONE FOMC meeting remains in 2025: December 9-10
- Maximum possible cuts in 2025: 3 (if Dec meeting cuts)
- Outcomes requiring 4+ cuts in 2025 are IMPOSSIBLE

REALITY CHECK: Is this outcome actually possible?
- Count the remaining events/meetings before the deadline
- If the required outcome exceeds what's physically possible, fair probability is <1%
- A market priced at 1% for an impossible outcome is CORRECTLY priced, not undervalued

Provide your analysis:
1. What is the TRUE probability of YES? (0-100%)
2. Your confidence level: low, medium, or high
3. Key reasoning - explicitly state if outcome is possible/impossible
4. Any time constraints?

Format as JSON:
{{"fair_probability": 65, "confidence": "medium", "reasoning": "...", "time_sensitive": false}}
"""

        # ChatGPT Analysis
        if self.use_chatgpt:
            try:
                response = call_chatgpt(
                    agent_id="chatgpt",
                    prior_messages=[{"role": "user", "content": prompt}],
                    session_goal=f"Analyze Polymarket: {market.question}",
                )
                if "error" not in response:
                    analysis = self._parse_ai_response(response.get("content", ""))
                    if analysis:
                        analysis["source"] = "chatgpt"
                        analyses.append(analysis)
                        LOG.debug(f"ChatGPT analysis: {analysis}")
            except Exception as e:
                LOG.warning(f"ChatGPT analysis failed: {e}")

        # Claude Analysis
        if self.use_claude:
            try:
                response = call_claude(
                    agent_id="claude",
                    prior_messages=[{"role": "user", "content": prompt}],
                    session_goal=f"Analyze Polymarket: {market.question}",
                )
                if "error" not in response:
                    analysis = self._parse_ai_response(response.get("content", ""))
                    if analysis:
                        analysis["source"] = "claude"
                        analyses.append(analysis)
                        LOG.debug(f"Claude analysis: {analysis}")
            except Exception as e:
                LOG.warning(f"Claude analysis failed: {e}")

        # If no AI available, log and return empty
        # Don't fall back to heuristic - bad signals are worse than no signals
        if not analyses:
            LOG.warning(f"No AI analysis available for {market.slug} - skipping (no heuristic fallback)")

        return analyses

    def _parse_ai_response(self, content: str) -> Optional[Dict]:
        """Parse AI response into analysis dict"""
        try:
            # Try to find JSON in response
            import re
            json_match = re.search(r'\{[^{}]+\}', content, re.DOTALL)
            if json_match:
                data = json.loads(json_match.group())
                return {
                    "fair_probability": float(data.get("fair_probability", 50)),
                    "confidence": data.get("confidence", "low"),
                    "reasoning": data.get("reasoning", ""),
                    "time_sensitive": data.get("time_sensitive", False),
                }
        except (json.JSONDecodeError, ValueError) as e:
            LOG.debug(f"Failed to parse AI response: {e}")

        return None

    def _heuristic_analysis(self, market: Market) -> Optional[Dict]:
        """Fallback when AI is unavailable - returns None to skip rather than guess.

        The old heuristic bet YES on anything <15% assuming it was underpriced.
        This led to betting on impossible outcomes (7 Fed rate cuts with 1 month left).

        Better to return no signal than a bad signal based on price alone.
        """
        # Don't generate signals without real analysis
        # A market at 1% might be correctly priced, not mispriced
        LOG.info(f"Skipping {market.question[:50]} - no AI analysis available, refusing to guess")
        return None

    def build_consensus_signal(self, market: Market, analyses: List[Dict]) -> Optional[IntelligentSignal]:
        """
        Build consensus from multiple analyses and create signal.
        """
        if not analyses:
            return None

        # Build consensus
        consensus = build_consensus(analyses)

        fair_prob = consensus["consensus_probability"]
        market_price = market.mid_price or market.last_price or 0.5

        # Determine side and edge
        if fair_prob > market_price:
            side = "YES"
            edge = fair_prob - market_price
        else:
            side = "NO"
            edge = market_price - fair_prob

        # Skip if edge too small
        if edge < self.min_edge:
            LOG.debug(f"Skipping {market.slug}: edge {edge:.2%} < min {self.min_edge:.2%}")
            return None

        # Skip if confidence too low
        conf_order = {"low": 0, "medium": 1, "high": 2}
        if conf_order.get(consensus["confidence"], 0) < conf_order.get(self.min_confidence, 1):
            LOG.debug(f"Skipping {market.slug}: confidence {consensus['confidence']} < {self.min_confidence}")
            return None

        # Score reasoning quality
        reasoning_score = score_reasoning({"reasoning": consensus["reasoning"]})

        # Determine order type based on spread and urgency
        order_type, limit_price, urgency = self._determine_order_strategy(market, side, edge)

        # Calculate position size using Kelly
        kelly_fraction = self._kelly_criterion(edge, consensus["confidence"])
        recommended_size = min(
            self.bankroll * kelly_fraction,
            self.bankroll * self.max_position_pct
        )

        # Get token ID
        token_id = market.token_id_yes if side == "YES" else market.token_id_no

        return IntelligentSignal(
            market_id=market.slug,
            token_id=token_id,
            question=market.question,
            side=side,
            fair_probability=fair_prob,
            market_price=market_price,
            edge=edge,
            confidence=consensus["confidence"],
            reasoning=consensus["reasoning"],
            reasoning_quality=reasoning_score["total_score"],
            num_analyses=consensus["num_analyses"],
            disagreement_detected=consensus["disagreement_detected"],
            spread_bps=market.spread_bps or 0,
            liquidity=market.liquidity,
            volume_24h=market.volume_24h,
            order_type=order_type,
            limit_price=limit_price,
            urgency=urgency,
            recommended_size_usd=recommended_size,
            kelly_fraction=kelly_fraction,
        )

    def _determine_order_strategy(
        self,
        market: Market,
        side: str,
        edge: float
    ) -> Tuple[str, Optional[float], str]:
        """
        Determine whether to use limit or market order.

        Strategy:
        - Wide spread + patient = LIMIT (capture spread, be the smart money)
        - Tight spread + urgent = MARKET (take liquidity before it moves)
        - Time-sensitive events = MARKET with urgency
        """
        spread_bps = market.spread_bps or 100

        # Get best prices
        if side == "YES":
            # We want to buy YES - be patient, post limit below ask
            best_bid = market.best_bid or (market.mid_price - 0.01) if market.mid_price else 0.5
            best_ask = market.best_ask or (market.mid_price + 0.01) if market.mid_price else 0.5

            if spread_bps > 200:  # Wide spread - use limit
                # Post just above best bid to be first in queue
                limit_price = min(best_bid + 0.01, best_ask - 0.01)
                return "limit", limit_price, "low"
            elif spread_bps > 100:  # Medium spread
                # Split the difference
                limit_price = (best_bid + best_ask) / 2
                return "limit", limit_price, "normal"
            else:  # Tight spread - just take it
                return "market", None, "normal"
        else:
            # We want to buy NO - similar logic but inverted
            if spread_bps > 200:
                return "limit", market.best_bid, "low"
            elif spread_bps > 100:
                return "limit", market.mid_price, "normal"
            else:
                return "market", None, "normal"

    def _kelly_criterion(self, edge: float, confidence: str) -> float:
        """
        Calculate Kelly fraction with confidence adjustment.

        Full Kelly = edge / odds
        We use fractional Kelly (25-50%) for safety.
        """
        # Confidence multiplier
        conf_mult = {"low": 0.25, "medium": 0.50, "high": 0.75}.get(confidence, 0.25)

        # Simple Kelly approximation
        kelly_full = edge * 2  # Assuming ~50% odds on average

        # Apply confidence multiplier and cap
        kelly_adj = kelly_full * conf_mult

        # Cap at 5% per position
        return min(kelly_adj, 0.05)

    def generate_signals(self, limit: int = 20) -> List[IntelligentSignal]:
        """
        Generate intelligent trading signals.

        Full pipeline:
        1. Fetch live markets
        2. Analyze each with AI
        3. Build consensus
        4. Filter and rank
        5. Return top signals
        """
        LOG.info("=" * 60)
        LOG.info("INTELLIGENT ALPHA ENGINE - Signal Generation")
        LOG.info("=" * 60)

        # Step 1: Fetch markets
        markets = self.fetch_live_markets(limit=limit * 2)

        if not markets:
            LOG.warning("No markets fetched!")
            return []

        # Step 2-3: Analyze and build signals
        signals = []
        for market in markets:
            LOG.info(f"\nAnalyzing: {market.question[:50]}...")

            # Get AI analyses
            analyses = self.analyze_market_with_ai(market)

            # Build consensus signal
            signal = self.build_consensus_signal(market, analyses)

            if signal:
                signals.append(signal)
                LOG.info(f"  ✓ Signal: {signal.side} edge={signal.edge:.1%} conf={signal.confidence}")
            else:
                LOG.debug(f"  ✗ No signal generated")

        # Step 4: Sort by edge * confidence
        conf_score = {"low": 1, "medium": 2, "high": 3}
        signals.sort(
            key=lambda s: s.edge * conf_score.get(s.confidence, 1),
            reverse=True
        )

        # Step 5: Return top signals
        top_signals = signals[:limit]

        LOG.info(f"\n{'=' * 60}")
        LOG.info(f"Generated {len(top_signals)} signals from {len(markets)} markets")
        LOG.info(f"{'=' * 60}")

        return top_signals

    def save_signals(self, signals: List[IntelligentSignal], output_path: Path):
        """Save signals to JSON file"""
        output = {
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "engine": "intelligent_alpha_v1",
            "bankroll": self.bankroll,
            "signal_count": len(signals),
            "total_recommended_size": sum(s.recommended_size_usd for s in signals),
            "signals": [s.to_dict() for s in signals]
        }

        with open(output_path, "w") as f:
            json.dump(output, f, indent=2)

        LOG.info(f"Saved {len(signals)} signals to {output_path}")


def main():
    """Main entry point"""
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(message)s"
    )

    # Load environment
    from dotenv import load_dotenv
    env_path = Path(__file__).parent.parent / ".env.polymarket"
    load_dotenv(env_path)

    # Also try to load OpenAI key
    openai_key = os.getenv("OPENAI_API_KEY")
    if not openai_key:
        LOG.warning("OPENAI_API_KEY not set - ChatGPT analysis disabled")

    # Initialize engine
    engine = IntelligentAlphaEngine(
        bankroll=10000.0,
        max_position_pct=0.05,
        min_edge=0.05,
        min_confidence="medium",
    )

    # Generate signals
    signals = engine.generate_signals(limit=15)

    # Save to state
    output_path = Path(__file__).parent.parent / "state" / "intelligent_signals.json"
    engine.save_signals(signals, output_path)

    # Print summary
    print("\n" + "=" * 70)
    print("INTELLIGENT ALPHA ENGINE - RESULTS")
    print("=" * 70)

    if not signals:
        print("\nNo signals generated. Check logs for details.")
        return

    print(f"\nTop {len(signals)} Signals:\n")

    for i, sig in enumerate(signals, 1):
        print(f"{i}. {sig.side} on: {sig.question[:50]}...")
        print(f"   Edge: {sig.edge:.1%} | Confidence: {sig.confidence}")
        print(f"   Market: {sig.market_price:.2f} → Fair: {sig.fair_probability:.2f}")
        print(f"   Order: {sig.order_type.upper()}" + (f" @ {sig.limit_price:.3f}" if sig.limit_price else ""))
        print(f"   Size: ${sig.recommended_size_usd:.2f} (Kelly: {sig.kelly_fraction:.1%})")
        print(f"   Reasoning: {sig.reasoning[:80]}...")
        print()

    total_size = sum(s.recommended_size_usd for s in signals)
    print(f"Total recommended deployment: ${total_size:.2f}")
    print(f"\nSignals saved to: {output_path}")


if __name__ == "__main__":
    main()
